### ISSUE TITLE
Poluted prototype

### ISSUE THREAD

**Issue by flafik** [leetm4n/type-schema#3]
Hello,
I've come into issue when one base class is inherited by multiple child classes.
It is caused by properties.push method while adding property - if the array comes from base class, then it will appear both in child and base. This will cause runtime exception InvalidTypeError from getType function.

Can be fixed by creating new array:

```typescript
export const addPropertyKey = (key: string, target: any) => {
  const properties = Reflect.getMetadata(MetadataKeys.PROPERTIES, target) as string[] | undefined;
  if (properties) {
    // properties.push(key); - polutes original prototype

    Reflect.defineMetadata(MetadataKeys.PROPERTIES, [...properties, key], target); // new array fixes problem
  } else {
    Reflect.defineMetadata(MetadataKeys.PROPERTIES, [key], target);
  }
};
```

**Comment by leetm4n** [comment]
Thanks for pointing this out, will fix it ASAP!
